---
title: "Week 3 Analysis"
author: "Jake Berberian"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r library, include = FALSE}
library(tidyverse)
library(ffanalytics)
library(lpSolve)
library(rPref)
library(plotly)
library(kableExtra)
library(tictoc)
```

```{r specs, include = FALSE}
week <- 3
n_sims <- 10000

scoring <- list(
  pass = list(
    pass_att = 0, pass_comp = 0, pass_inc = 0, pass_yds = 0.04, pass_tds = 4,
    pass_int = -1, pass_40_yds = 0,  pass_300_yds = 0, pass_350_yds = 0,
    pass_400_yds = 0
  ),
  rush = list(
    all_pos = TRUE,
    rush_yds = 0.1,  rush_att = 0, rush_40_yds = 0, rush_tds = 6,
    rush_100_yds = 0, rush_150_yds = 0, rush_200_yds = 0),
  rec = list(
    all_pos = TRUE,
    rec = 0.5, rec_yds = 0.1, rec_tds = 6, rec_40_yds = 0, rec_100_yds = 0,
    rec_150_yds = 0, rec_200_yds = 0
  ),
  misc = list(
    all_pos = TRUE,
    fumbles_lost = -2, fumbles_total = 0,
    sacks = 0, two_pts = 2
  ),
  ret = list(
    all_pos = TRUE,
    return_tds = 6, return_yds = 0
  ),
  dst = list(
    dst_fum_rec = 2,  dst_int = 2, dst_safety = 2, dst_sacks = 1, dst_td = 6,
    dst_blk = 2, dst_ret_yds = 0, dst_pts_allowed = 0
  ),
  pts_bracket = list(
    list(threshold = 0, points = 10),
    list(threshold = 1, points = 7),
    list(threshold = 7, points = 4),
    list(threshold = 14, points = 1),
    list(threshold = 21, points = 0),
    list(threshold = 28, points = -1),
    list(threshold = 35, points = -4)
  )
)
```


```{r proj_data, include = FALSE}
# Projection data
sources <- c("ESPN", "FantasyData", "FantasyPros", "FantasySharks", 
             "FFToday", "NumberFire", "Yahoo", "FantasyFootballNerd", 
             "RTSports", "Walterfootball")

scrape <- scrape_data(src = sources,
                      pos = c('QB', 'RB', 'WR', 'TE', 'DST'),
                      season = 2020, 
                      week = week)

projections <- projections_table(scrape, scoring_rules = scoring) %>%
  add_player_info()
```


```{r fanduel_data, include = FALSE}
fan_duel <- read_csv("~/Fall_2020/MATH-390/Data/FanDuel-NFL-2020-09-27-50179-players-list.csv") %>% 
  filter(is.na(`Injury Details`) | `Injury Indicator` == "Q") %>%
  mutate(`Last Name` = str_remove_all(`Last Name`, "((?i)III(?-i))"),
         `Last Name` = str_remove_all(`Last Name`, "((?i)II(?-i))"),
         `Last Name` = str_remove_all(`Last Name`, "((?i)IV(?-i))"),
         `Last Name` = str_remove_all(`Last Name`, "((?i)V(?-i))"),
         `Last Name` = str_remove_all(`Last Name`, "((?i)Jr.(?-i))"),
         `Last Name` = str_remove_all(`Last Name`, "((?i)Sr.(?-i))"),
         Name = str_c(`First Name`, `Last Name`, sep = " ")) %>% 
  select(-c(Id, Tier, X15, X16, Game)) %>%
  mutate(position = case_when(
    Position == "D" ~ "DST",
    TRUE ~ as.character(Position)
  )) 
```


```{r actual_data, include = FALSE}
results <- read_csv("~/Fall_2020/MATH-390/Data/week3_results.csv") %>% 
  mutate(`First Name` = str_remove_all(`First Name`, "\\."),
         Name = str_c(`First Name`, `Last Name`, sep = " "), 
         position = case_when(
           Pos == "Def" ~ "DST",
           TRUE ~ as.character(Pos)
           )) %>% 
  rename("Salary" = `FD salary`, "actual_pts" = `FD points`) %>% 
  select(Name, position, actual_pts, `Salary`)
```


```{r sim_function, include = FALSE}
# Simulation time

generate_lineup <- function(n){
  pred_sal <- projections %>% 
    filter(avg_type == "robust") %>% 
    mutate(Name = str_c(first_name, last_name, sep = " ")) %>% 
    inner_join(fan_duel, by = c("Name", "position")) %>% 
    select(position, Name, team, points, Salary, sd_pts) %>% 
    drop_na(points, Salary) %>% 
    group_by(Name) %>% 
    mutate(sal_max = max(Salary)) %>%
    filter(Salary == sal_max) %>%
    group_by(Name) %>% 
    mutate(pts_pred = rnorm(1, points, sd_pts), lineup = n) %>% 
    select(-sal_max)
  
  
    obj <- pred_sal$pts_pred
    
    mat <- rbind(t(model.matrix(~ position + 0,pred_sal)), 
               t(model.matrix(~ position + 0,pred_sal)), 
               rep(1, nrow(pred_sal)), pred_sal$Salary)
    
    dir <- c("=","=","<=","<=","<=", "=","=",">=",">=",">=","=","<=")
    
    rhs <- c(1, 1, 3, 2, 4, 1, 1, 2, 1, 3, 9, 60000)
  
  result <- lp("max", obj, mat, dir, rhs, all.bin = TRUE)   
  
  results <- pred_sal[which(result$solution == 1),]
  
  return(results)
}
```

```{r sim_time, echo=FALSE}
tic()
sim_lu <- map_df(1:n_sims, generate_lineup) %>%
  rename(pts_base = points) %>%  
  mutate(position = factor(position, 
                           levels = c("QB", "RB", "WR", "TE", "DST"))) %>% 
  select(lineup, Name, team, position, pts_base, pts_pred, sd_pts, Salary)
toc()
```


```{r join_pareto, echo = FALSE}
lu_df <- sim_lu %>% 
  inner_join(results) %>% 
  group_by(lineup) %>% 
  summarise(points = sum(pts_pred),
            std_dev = sum(sd_pts),
            actual = sum(actual_pts)) %>% 
  ungroup()

pto <- psel(lu_df, low(std_dev) * high(points))
```


```{r results, echo=FALSE}
sim_lu <- sim_lu %>% 
  full_join(results) %>%  
  mutate(position = factor(position, 
                           levels = c("QB", "RB", "WR", "TE", "DST")))

pto %>% 
  left_join(sim_lu, by = "lineup") %>% 
  group_by(lineup) %>% 
  arrange(points, position, desc(Salary)) %>% 
  mutate(error = (abs((actual - points)) / points) * 100,
         sd_error = abs((actual - points) / std_dev)) %>% 
  select(lineup, points, std_dev, actual, error, sd_error, Name, team, 
         position, pts_pred, sd_pts, actual_pts, Salary) %>% 
  mutate_if(is.numeric, round, 2) %>% 
  knitr::kable() %>% 
  kable_styling(fixed_thead = T) %>%
  column_spec(1:6, bold = TRUE) %>%
  collapse_rows(columns = 1:6, valign = 'top') %>%
  scroll_box(height = '700px', width = '100%')
```



